### ISSUE TITLE
 prediction = model.predict([gray_image.reshape(89,100,1)]) ValueError: cannot reshape array of size 7500 into shape (89,100,1)

### ISSUE THREAD

**Issue by aminhoney** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#10]

**Comment by aminhoney** [comment]
prediction = model.predict([gray_image.reshape(89,100,1)])
ValueError: cannot reshape array of size 7500 into shape (89,100,1)

would you try to resolve this error with scipy.misc ??

**Comment by SparshaSaha** [comment]
I donot see this issue on my system.
YOu can change this line to :
prediction = model.predict([gray_image.reshape(75,100,1)])..
That should fix it..
