### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by ashReal** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#2]
i am trying to create dataset for peace sign. But new threshold images are not saved in my PeaceTest folder even after i changed code in line 103

problem sloved

**Comment by SparshaSaha** [comment]
So you have solved your problem it seems..Cool.. Do tell me if you find this repository interesting and useful :).. @ashReal
