### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kavin256** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#3]
AttributeError: 'NoneType' object has no attribute 'shape'.

In ContinuousGesturePredictor, I tried moving 'import cv2' line to the top. And it SOLVED the issue.

**Comment by SparshaSaha** [comment]
I'll check and get back to you in a few days

**Comment by hadeeratef4** [comment]
AttributeError: 'NoneType' object has no attribute 'shape'.

I have the same issue.  can help me  ?

**Comment by mohammed-Emad** [comment]
Check the cam or check the video used,
This error does occur when there is a problem reading the camera or video.

He inquires about the shape class,
But the value of the frame now equals None,
There are no classes there so this is a mistake.
It was supposed to make a condition to alert you to the lack of input to understand the problem without entering into other labyrinths.

For example

```python3
if ret==True:
   ...your code..
else:
  error input and break
```
or real example
```python3
while(True):
        # get the current frame
        (grabbed, frame) = camera.read()
        if not grabbed: #is true
            print("Error input chk your[cam Or video]")
            break
        # resize the frame
        frame = imutils.resize(frame, width = 700)

        # flip the frame so that it is not the mirror view
        frame = cv2.flip(frame, 1)

        # clone the frame
        clone = frame.copy()

        # get the height and width of the frame
        (height, width) = frame.shape[:2]
```
Thanks, good luck

**Comment by mohammed-Emad** [comment]
or cam error port?
```python
camera = cv2.VideoCapture(0)
```
try -1 vs 0
```python
camera = cv2.VideoCapture(-1)
```
see
[cv2-videocapture-open-always-returns-false](https://stackoverflow.com/questions/21792909/cv2-videocapture-open-always-returns-false)

**Comment by SparshaSaha** [comment]
Hey @mohammed-Emad your point seems right. I should have included a check for the cam capture before getting into action. I would request you to raise a Pull Request to fix the Issue. I can then merge it in accordingly. Thanks.

**Comment by mohammed-Emad** [comment]
Hi @SparshaSaha , I will start with that now
Thank you

**Comment by SparshaSaha** [comment]
A fix for this issue has been put in by @mohammed-Emad . Thus  closing this
