### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by kavin256** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#4]
ValueError: need more than 2 values to unpack when running ContinuousGesturePredictor.py

**Comment by kavin256** [comment]
I changed the line 
(_, cnts, _) = cv2.findContours(thresholded.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

into

(cnts, _) = cv2.findContours(thresholded.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

it SOLVED.

**Comment by SparshaSaha** [comment]
I'll have a look and get back to you

**Comment by lenikhilsingh** [comment]
the function cv2.findContours() has been changed to return only the contours and the hierarchy and not ret


`contours,hierachy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)` , works perfectly.
