### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint

### ISSUE THREAD

**Issue by adeebx1** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#5]
C:\Users\adeebx1\Documents\GitHub\Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network>ContinuousGesturePredictor.py
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
WARNING:tensorflow:From C:\Users\adeebx1\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From C:\Users\adeebx1\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\objectives.py:66: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "C:\Users\adeebx1\Documents\GitHub\Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network\ContinuousGesturePredictor.py", line 206, in <module>
    model.load("GestureRecogModel.tfl")
  File "C:\Users\adeebx1\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\Users\adeebx1\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\Users\adeebx1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1538, in restore
    + compat.as_text(save_path))
**ValueError: The passed save_path is not a valid checkpoint: C:\Users\adeebx1\Documents\GitHub\Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network\GestureRecogModel.tfl**

how to solve this issue!!

**Comment by lenikhilsingh** [comment]
Even i get the same error. Somebody please solve it!

**Comment by ViswaSaiRaman** [comment]
@adeebx1 before you run the ContinuousGesturePredictor.py, you got to train you model by running ModelTrainer.ipynb in the Jupyter.
Once you are done with that, it would generate the GestureRecogModel.tfl in your project folder.
The error which you are getting now is because you do not have GestureRecogModel.tfl in you project folder.
Hope it helps

**Comment by SparshaSaha** [comment]
@adeebx1 and @ViswaSaiRaman  the trained model in my PC was around 60 to 70 MB. Github doesn't allow us to upload such a single large file. Thus i couldn't upload the trained model. 
Now, the best work around that is to train the model yourself on your local. So, you can go ahead and run the ModelTrainer code before going for the prediction. Hope this helps. :)
