### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by suheyyl** [SparshaSaha/Hand-Gesture-Recognition-Using-Background-Elllimination-and-Convolution-Neural-Network#6]
What version of TensorFlow and tflearn are you using?

**Comment by SparshaSaha** [comment]
I do not remember explicitly. When i created the repo I used the latest version then. But i believe it should work with the latest versions.

**Comment by zzerr0** [comment]
Use 1.5 version of tensorflow otherwise  you'll have illegal operation error
